name:                union
version:             0.1.0.1
github:              "https://github.com/bird1235456"
license:             BSD3
author:              "Stum"
maintainer:          "mark@ComputerDevelopersUnion.com"
copyright:           "2020 Author name here"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  union-exe:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union

tests:
  union-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union
